// AUTH

export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";

//MODALS

export const CHANGE_MODAL_STATE = "CHANGE_MODAL_STATE";

//CONTEXT

export const CLEAR_CONTEXT = "CLEAR_CONTEXT";

//FOLDERS

export const GET_FOLDERS = "GET_FOLDERS";
export const CREATE_FOLDER = "CREATE_FOLDER";
export const SELECT_FOLDER_MODFICATION = "SELECT_FOLDER_MODFICATION";
export const UNSELECT_FOLDER_MODFICATION = "UNSELECT_FOLDER_MODFICATION";
export const SAVE_FOLDER_CHANGES = "SAVE_FOLDER_CHANGES";
export const DELETE_FOLDER = "DELETE_FOLDER";
export const SELECT_FOLDER = "SELECT_FOLDER";

//TASK

export const FETCHING_TASKS = "FETCHING_TASKS";
export const GET_TASKS = "GET_TASKS";
export const CREATE_TASK = "CREATE_TASK";
export const SELECT_TASK_MODFICATION = "SELECT_TASK_MODFICATION";
export const UNSELECT_TASK_MODFICATION = "UNSELECT_TASK_MODFICATION";
export const SAVE_TASK_CHANGES = "SAVE_TASK_CHANGES";
export const DELETE_TASK = "DELETE_TASK";
